### ISSUE TITLE
Solve Picking Numbers 

### ISSUE THREAD

**Issue by Alpha17-2** [Alpha17-2/Hackerank_problems#1]
[Link to problem](https://www.hackerrank.com/challenges/picking-numbers/problem)

**Comment by subhodynamics** [comment]
Ok

**Comment by Alpha17-2** [comment]
@subhodynamics You are now assigned to solve the program !!

**Comment by technicalreju** [comment]
Hey buddy, I would like to solve this problem.

**Comment by Alpha17-2** [comment]
> Hey buddy, I would like to solve this problem.

This task has been already assigned to the mentioned participant , I will be raising some new issues soon

**Comment by Alpha17-2** [comment]
Closing the issue
Solved by @subhodynamics
