### ISSUE TITLE
Digit Removal

### ISSUE THREAD

**Issue by subhodynamics** [Alpha17-2/Hackerank_problems#13]
[problem link](https://www.codechef.com/OCT21C/problems/DIGITREM)

**Comment by subhodynamics** [comment]
I want to work on this.

**Comment by Alpha17-2** [comment]
I really appreciate your interest towards solving problems but this repository is strictly made for Hackerrank problems , I hope you come back with some exciting problems from the above mentioned platform . 
Thank you !!
