### ISSUE TITLE
Angry Professor

### ISSUE THREAD

**Issue by Alpha17-2** [Alpha17-2/Hackerank_problems#2]
[Problem Link](https://www.hackerrank.com/challenges/angry-professor/problem)

**Comment by technicalreju** [comment]
Hey there, Can you assign me this problem? I would be happy to help you in this issue.

**Comment by Alpha17-2** [comment]
Sure mate !! Go ahead 
Keep in mind that your solution should pass all the test cases provided by Hackerrank 
Happy contributing !!

**Comment by Alpha17-2** [comment]
The problem is open for all now
