### ISSUE TITLE
Electronics Shop

### ISSUE THREAD

**Issue by Alpha17-2** [Alpha17-2/Hackerank_problems#3]
[Problem Link](https://www.hackerrank.com/challenges/electronics-shop/problem)

**Comment by shreyaa2410** [comment]
I'll solve this problem.
please assign!

**Comment by Alpha17-2** [comment]
Sure !! Go ahead .
Make sure your solution code passes all the test cases provided by Hackerrank .
Happy Contributing.

**Comment by Alpha17-2** [comment]
#4 Closing the issue .
 Solved by @shreyaa2410
